theme: jekyll-theme-minimal
title: [Kaz Gunning's PhD Defense]
site.github.is_user_page: [false]
description: "<strong>WHEN </strong> <br/>

Fri, Aug 21, 2020<br/>2:00 PDT<br/><br/>

<strong>WHERE TO WATCH </strong><br/>


<a href=\"https://stanford.zoom.us/j/93378078930?pwd=YWNyS2hVbFRLWGJzeTV4MWV5NzYzQT09"  target=\"_blank\" >Zoom <small>Stream + interaction in Zoom</small></a>
<br/>
<a href=\"https://youtube.com\" target=\"_blank\">Youtube <small>Stream only in your browser </small></a>


"
