theme: jekyll-theme-minimal
title: [Kaz Gunning's PhD Defense]
github.is_user_page: false 
description: "<strong>WHEN</strong> <br/>

Fri, Aug 21, 2020<br/>2:00 PDT<br/><br/>

<strong>WHERE TO WATCH</strong><br/>


<a href=\"https://zoom.stanford.edu\">Zoom <small> if u want me see ur face</small></a>
<br/>
<a href=\"youtube.com\">Youtube <small> no see ur face :(</small></a>


"
