theme: jekyll-theme-minimal
title: [Kaz Gunning's PhD Defense]

description: "**WHEN:**<strong>ZIP File</strong> <br/>Fri, Aug 21, 2020<br/>2:00 PDT<br/><br/>WHERE TO WATCH<br/>[Zoom](http://github.com) // YouTube"
